from fastapi import HTTPException, status

from app.models.screening_session import ScreeningSession
from app.models.session_metrics import SessionMetrics
from app.repositories.unit_of_work import UnitOfWork
from app.schemas.auth import AuthUserResponse
from app.schemas.session import (
    DashboardSummaryResponse,
    SessionCreate,
    SessionListResponse,
    SessionMetricsResponse,
    SessionReportResponse,
    SessionResponse,
    TestPresetResponse,
)
from app.services.metrics_service import risk_from_metrics

REPORT_DISCLAIMER = (
    "This report is generated by NeuroEyeAI as a clinical decision-support aid. "
    "It is not a standalone diagnosis and must be interpreted by a licensed clinician."
)


def _metrics_response(metrics: SessionMetrics | None) -> SessionMetricsResponse | None:
    if metrics is None:
        return None
    risk = metrics.extras.get("risk_level") if metrics.extras else None
    if not isinstance(risk, str):
        risk = risk_from_metrics(
            detection_rate=metrics.detection_rate,
            fixation_stability=metrics.fixation_stability,
            saccade_amplitude=metrics.saccade_amplitude,
        )
    return SessionMetricsResponse(
        session_id=metrics.session_id,
        sample_count=metrics.sample_count,
        mean_fps=metrics.mean_fps,
        detection_rate=metrics.detection_rate,
        mean_latency_ms=metrics.mean_latency_ms,
        fixation_stability=metrics.fixation_stability,
        saccade_amplitude=metrics.saccade_amplitude,
        extras=metrics.extras or {},
        risk_level=risk,
    )


class SessionService:
    async def _to_response(
        self,
        uow: UnitOfWork,
        session: ScreeningSession,
        *,
        include_metrics: bool = False,
    ) -> SessionResponse:
        patient = await uow.patients.get_by_id(session.patient_id)
        preset = await uow.test_presets.get_by_id(session.preset_id)
        metrics = None
        if include_metrics:
            metrics = await uow.session_metrics.get_by_session_id(session.id)

        return SessionResponse(
            id=session.id,
            patient_id=session.patient_id,
            patient_name=patient.display_name if patient else session.patient_id,
            clinician_id=session.clinician_id,
            preset_id=session.preset_id,
            preset_code=preset.code if preset else "",
            preset_name=preset.name if preset else "",
            status=session.status,
            started_at=session.started_at,
            ended_at=session.ended_at,
            abort_reason=session.abort_reason,
            metrics=_metrics_response(metrics),
        )

    async def list_presets(
        self,
        uow: UnitOfWork,
        current_user: AuthUserResponse,
    ) -> list[TestPresetResponse]:
        presets = await uow.test_presets.list_for_tenant(current_user.tenant_id)
        return [
            TestPresetResponse(
                id=preset.id,
                code=preset.code,
                name=preset.name,
                description=preset.description,
                config=preset.config or {},
            )
            for preset in presets
        ]

    async def list_sessions(
        self,
        uow: UnitOfWork,
        current_user: AuthUserResponse,
        *,
        patient_id: str | None = None,
        page: int = 1,
        page_size: int = 20,
    ) -> SessionListResponse:
        items, total = await uow.screening_sessions.list_for_tenant(
            current_user.tenant_id,
            patient_id=patient_id,
            page=page,
            page_size=page_size,
        )
        responses = [
            await self._to_response(uow, session, include_metrics=True) for session in items
        ]
        return SessionListResponse(
            items=responses,
            total=total,
            page=page,
            page_size=page_size,
        )

    async def get_session(
        self,
        uow: UnitOfWork,
        current_user: AuthUserResponse,
        session_id: str,
        *,
        include_metrics: bool = True,
    ) -> SessionResponse:
        session = await uow.screening_sessions.get_for_tenant(
            session_id,
            current_user.tenant_id,
        )
        if session is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found")
        return await self._to_response(uow, session, include_metrics=include_metrics)

    async def create_session(
        self,
        uow: UnitOfWork,
        current_user: AuthUserResponse,
        body: SessionCreate,
    ) -> SessionResponse:
        patient = await uow.patients.get_for_tenant(body.patient_id, current_user.tenant_id)
        if patient is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Patient not found")
        preset = await uow.test_presets.get_for_tenant(body.preset_id, current_user.tenant_id)
        if preset is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Preset not found")

        session = ScreeningSession(
            tenant_id=current_user.tenant_id,
            patient_id=patient.id,
            clinician_id=current_user.id,
            preset_id=preset.id,
            status="pending",
        )
        await uow.screening_sessions.add(session)
        return await self._to_response(uow, session)

    async def get_report(
        self,
        uow: UnitOfWork,
        current_user: AuthUserResponse,
        session_id: str,
    ) -> SessionReportResponse:
        session = await self.get_session(uow, current_user, session_id, include_metrics=True)
        return SessionReportResponse(
            session=session,
            metrics=session.metrics,
            disclaimer=REPORT_DISCLAIMER,
        )

    async def dashboard_summary(
        self,
        uow: UnitOfWork,
        current_user: AuthUserResponse,
    ) -> DashboardSummaryResponse:
        patient_count = await uow.patients.count_for_tenant(current_user.tenant_id)
        session_count = await uow.screening_sessions.count_for_tenant(current_user.tenant_id)
        completed = await uow.screening_sessions.count_for_tenant(
            current_user.tenant_id,
            status="completed",
        )
        sessions, _ = await uow.screening_sessions.list_for_tenant(
            current_user.tenant_id,
            page=1,
            page_size=200,
        )
        at_risk = 0
        for session in sessions:
            metrics = await uow.session_metrics.get_by_session_id(session.id)
            risk = _metrics_response(metrics)
            if risk and risk.risk_level in {"high", "critical"}:
                at_risk += 1

        return DashboardSummaryResponse(
            patient_count=patient_count,
            session_count=session_count,
            completed_session_count=completed,
            at_risk_count=at_risk,
        )


session_service = SessionService()
