/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthRecoveryPasswordRouteImport } from './routes/_auth/recovery-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPatientsRouteImport } from './routes/_app/patients'
import { Route as AppPatientsPatientIdRouteImport } from './routes/_app/patients_.$patientId'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppEyetrackingSessionRouteImport } from './routes/_app/eyetracking.session'
import { Route as AppEyetrackingSessionPatientIdRouteImport } from './routes/_app/eyetracking.session_.$patientId'
import { Route as AppReportsSessionIdRouteImport } from './routes/_app/reports.$sessionId'
import { Route as AppAdminTenantsRouteImport } from './routes/_app/admin.tenants'
import { Route as AppAdminTenantsTenantIdRouteImport } from './routes/_app/admin.tenants_.$tenantId'
import { Route as AppAdminAccountsRouteImport } from './routes/_app/admin.accounts'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoveryPasswordRoute = AuthRecoveryPasswordRouteImport.update({
  id: '/recovery-password',
  path: '/recovery-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/patients_/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppEyetrackingSessionRoute = AppEyetrackingSessionRouteImport.update({
  id: '/eyetracking/session',
  path: '/eyetracking/session',
  getParentRoute: () => AppRoute,
} as any)
const AppEyetrackingSessionPatientIdRoute = AppEyetrackingSessionPatientIdRouteImport.update({
  id: '/eyetracking/session_/$patientId',
  path: '/eyetracking/session/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSessionIdRoute = AppReportsSessionIdRouteImport.update({
  id: '/reports/$sessionId',
  path: '/reports/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsRoute = AppAdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsTenantIdRoute = AppAdminTenantsTenantIdRouteImport.update({
  id: '/admin/tenants_/$tenantId',
  path: '/admin/tenants/$tenantId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAccountsRoute = AppAdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/patients': typeof AppPatientsRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/sessions': typeof AppSessionsRoute
  '/eyetracking/session': typeof AppEyetrackingSessionRoute
  '/eyetracking/session/$patientId': typeof AppEyetrackingSessionPatientIdRoute
  '/reports/$sessionId': typeof AppReportsSessionIdRoute
  '/admin/tenants': typeof AppAdminTenantsRoute
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/admin/accounts': typeof AppAdminAccountsRoute
  '/login': typeof AuthLoginRoute
  '/recovery-password': typeof AuthRecoveryPasswordRoute
  '/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/patients': typeof AppPatientsRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/sessions': typeof AppSessionsRoute
  '/eyetracking/session': typeof AppEyetrackingSessionRoute
  '/eyetracking/session/$patientId': typeof AppEyetrackingSessionPatientIdRoute
  '/reports/$sessionId': typeof AppReportsSessionIdRoute
  '/admin/tenants': typeof AppAdminTenantsRoute
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/admin/accounts': typeof AppAdminAccountsRoute
  '/login': typeof AuthLoginRoute
  '/recovery-password': typeof AuthRecoveryPasswordRoute
  '/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/patients_/$patientId': typeof AppPatientsPatientIdRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/eyetracking/session': typeof AppEyetrackingSessionRoute
  '/_app/eyetracking/session_/$patientId': typeof AppEyetrackingSessionPatientIdRoute
  '/_app/reports/$sessionId': typeof AppReportsSessionIdRoute
  '/_app/admin/tenants': typeof AppAdminTenantsRoute
  '/_app/admin/tenants_/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/_app/admin/accounts': typeof AppAdminAccountsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recovery-password': typeof AuthRecoveryPasswordRoute
  '/_auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/patients'
    | '/patients/$patientId'
    | '/sessions'
    | '/eyetracking/session'
    | '/eyetracking/session/$patientId'
    | '/reports/$sessionId'
    | '/admin/tenants'
    | '/admin/tenants/$tenantId'
    | '/admin/accounts'
    | '/login'
    | '/recovery-password'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/patients'
    | '/patients/$patientId'
    | '/sessions'
    | '/eyetracking/session'
    | '/eyetracking/session/$patientId'
    | '/reports/$sessionId'
    | '/admin/tenants'
    | '/admin/tenants/$tenantId'
    | '/admin/accounts'
    | '/login'
    | '/recovery-password'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/privacy-policy'
    | '/terms'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/patients'
    | '/_app/patients_/$patientId'
    | '/_app/sessions'
    | '/_app/eyetracking/session'
    | '/_app/eyetracking/session_/$patientId'
    | '/_app/reports/$sessionId'
    | '/_app/admin/tenants'
    | '/_app/admin/tenants_/$tenantId'
    | '/_app/admin/accounts'
    | '/_auth/login'
    | '/_auth/recovery-password'
    | '/_auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recovery-password': {
      id: '/_auth/recovery-password'
      path: '/recovery-password'
      fullPath: '/recovery-password'
      preLoaderRoute: typeof AuthRecoveryPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients_/$patientId': {
      id: '/_app/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eyetracking/session': {
      id: '/_app/eyetracking/session'
      path: '/eyetracking/session'
      fullPath: '/eyetracking/session'
      preLoaderRoute: typeof AppEyetrackingSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eyetracking/session_/$patientId': {
      id: '/_app/eyetracking/session_/$patientId'
      path: '/eyetracking/session/$patientId'
      fullPath: '/eyetracking/session/$patientId'
      preLoaderRoute: typeof AppEyetrackingSessionPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/$sessionId': {
      id: '/_app/reports/$sessionId'
      path: '/reports/$sessionId'
      fullPath: '/reports/$sessionId'
      preLoaderRoute: typeof AppReportsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants': {
      id: '/_app/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AppAdminTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants_/$tenantId': {
      id: '/_app/admin/tenants_/$tenantId'
      path: '/admin/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AppAdminTenantsTenantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/accounts': {
      id: '/_app/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AppAdminAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppEyetrackingSessionRoute: typeof AppEyetrackingSessionRoute
  AppEyetrackingSessionPatientIdRoute: typeof AppEyetrackingSessionPatientIdRoute
  AppReportsSessionIdRoute: typeof AppReportsSessionIdRoute
  AppAdminTenantsRoute: typeof AppAdminTenantsRoute
  AppAdminTenantsTenantIdRoute: typeof AppAdminTenantsTenantIdRoute
  AppAdminAccountsRoute: typeof AppAdminAccountsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppEyetrackingSessionRoute: AppEyetrackingSessionRoute,
  AppEyetrackingSessionPatientIdRoute: AppEyetrackingSessionPatientIdRoute,
  AppReportsSessionIdRoute: AppReportsSessionIdRoute,
  AppAdminTenantsRoute: AppAdminTenantsRoute,
  AppAdminTenantsTenantIdRoute: AppAdminTenantsTenantIdRoute,
  AppAdminAccountsRoute: AppAdminAccountsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoveryPasswordRoute: typeof AuthRecoveryPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoveryPasswordRoute: AuthRecoveryPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
